export const SITE = {
  url: "https://ezforhamza.com",
  name: "Hamza Tanveer",
  title: "Hamza Tanveer — Full-Stack & Mobile Developer",
  shortTitle: "Hamza Tanveer",
  description:
    "Hamza Tanveer — full-stack & mobile developer building Flutter apps and AI-powered web platforms. Creator of HeyInterests & AIumni. Open for freelance work.",
  jobTitle: "Full-Stack & Mobile Developer",
  locality: "Sahiwal",
  country: "Pakistan",
  email: "hamzatanveer4347@gmail.com",
  university: "COMSATS University Islamabad",
  updated: "2026-06-25",
  keywords: [
    "Hamza Tanveer",
    "Hamza Tanveer developer",
    "HeyInterests",
    "AIumni",
    "AIumni Network",
    "Flutter developer",
    "mobile app developer",
    "full-stack developer",
    "React developer",
    "Next.js developer",
    "AI app developer",
    "Pakistan developer",
    "freelance developer Upwork",
  ],
  social: {
    github: "https://github.com/ezforhamza",
    upwork: "https://www.upwork.com/freelancers/~014e1746ed64a8ed7d",
    instagram: "https://www.instagram.com/ezforhamza",
    linkedin: "https://www.linkedin.com/in/ezforhamza/",
  },
  projects: [
    { name: "HeyInterests", url: "https://heyinterests.com/" },
    { name: "AIumni", url: "https://aiumni.co/" },
  ],
} as const;
